### ISSUE TITLE
ERROR for try to run the train demo

### ISSUE THREAD

**Issue by hokiwood-geek** [chico2121/bpe#6]
It seems train_bpe.py should be directly under the bpe-master dir. But after I did it and run the demo train command, error message came out as above :(

windows10
python3.8.6
all the dataset has been placed.

![屏幕截图 2021-05-09 220851](https://user-images.githubusercontent.com/56180349/117575160-306ee100-b113-11eb-823d-a061fd668141.png)

**Comment by BAILOOL** [comment]
@hokiwood-geek sorry for late reply. Have you processed the dataset as mentioned in the [guide](https://github.com/chico2121/SARA_Dataset#downloading-and-preprocessing-the-sara)?

`train_bpe.py` does not have to be under bpe-master dir. This repo assumes bpe-master to be the working dir. In your case you have to `export PYTHONPATH=$PYTHONPATH:/absolute-path-to/bpe-master`

I think OSError occurs due to the invalid path. Specifically, the error might be caused by `bpe_cache. \x08pe` part inside the path.
